export type MBTIType =
  | "INTJ" | "INTP" | "ENTJ" | "ENTP"
  | "INFJ" | "INFP" | "ENFJ" | "ENFP"
  | "ISTJ" | "ISFJ" | "ESTJ" | "ESFJ"
  | "ISTP" | "ISFP" | "ESTP" | "ESFP";

export type Squad = "Visionary" | "Harmonizer" | "Guardian" | "Explorer";

export interface MBTIProfile {
  type: MBTIType;
  squad: Squad;
  squadColor: string;
  nickname: string;
  nicknameEn: string;
  emoji: string;
  tagline: string;
  description: string;
  strengths: string[];
  weaknesses: string[];
  emotionalIntelligence: string;
  selfLoveGuidance: string;
  shadowWork: string;
  coreValues: string[];
  loveLanguage: string[];
  careerPaths: string[];
  romanticStyle: string;
  socialDynamics: string;
  purpose: string;
  famousPeople: string[];
}

export const MBTI_PROFILES: Record<MBTIType, MBTIProfile> = {
  INTJ: {
    type: "INTJ",
    squad: "Visionary",
    squadColor: "#7C3AED",
    nickname: "Si Arsitek Masa Depan",
    nicknameEn: "The Architect",
    emoji: "🏛️",
    tagline: "Merancang masa depan dari keheningan yang dalam",
    description: "Kamu adalah pemikir strategis yang memiliki visi jauh ke depan. Di balik ketenangan itu, ada mesin berpikir yang tidak pernah berhenti. Kamu tahu apa yang kamu mau, tapi sering lupa untuk merasakan perjalanannya.",
    strengths: ["Berpikir jangka panjang", "Mandiri dan determinasi tinggi", "Analitis dan strategis", "Perfeksionis produktif", "Percaya diri dalam keputusan"],
    weaknesses: ["Terlalu kritis pada diri sendiri", "Sulit ekspresikan emosi", "Bisa terlihat arogan", "Overthinking dan paralysis", "Sulit menerima kritik"],
    emotionalIntelligence: "Kamu cenderung memproses emosi secara internal dan sering disconnect dari perasaan. Kamu lebih nyaman dengan logika daripada vulnerability. Blind spot terbesar kamu: mengabaikan kebutuhan emosional orang-orang yang kamu sayangi karena kamu pikir 'logic is enough'.",
    selfLoveGuidance: "INTJ, perjalanan self-love kamu dimulai dari accepting bahwa imperfection itu bukan kegagalan — itu human. Perfeksionisme kamu adalah pelindung, bukan identitas. Coba ini: every day, list satu hal yang kamu lakukan 'cukup baik' tanpa harus sempurna. Rest bukan laziness — itu strategic recovery.",
    shadowWork: "Shadow INTJ adalah sisi yang takut dilihat lemah, yang memendam emosi sampai meledak, dan yang sabotase hubungan dengan standar yang tidak realistis. Acknowledge: kamu butuh orang lain, dan itu bukan kelemahan.",
    coreValues: ["Kompetensi", "Otonomi", "Kebenaran", "Inovasi", "Integritas"],
    loveLanguage: ["Quality time (intens dan meaningful)", "Acts of service", "Words of affirmation (butuh tapi jarang minta)"],
    careerPaths: ["Arsitek / Urban Planner", "Data Scientist / AI Engineer", "Pengacara / Hakim", "Strategic Consultant", "Penulis / Peneliti", "Founder / CEO"],
    romanticStyle: "Kamu setia, intens, dan all-in ketika sudah commit. Tapi kamu perlu waktu lama untuk trust seseorang. Partner yang cocok: yang menghargai kemandirian kamu dan tidak terlalu butuh external validation.",
    socialDynamics: "Kamu memilih kualitas dibanding kuantitas dalam pertemanan. Lingkaran sosial kamu kecil tapi dalam. Kamu mungkin terlihat dingin pada orang baru — tapi itu bukan kurang peduli, itu cara kamu melindungi diri.",
    purpose: "Kamu dipanggil untuk membangun sistem, solusi, dan visi yang bertahan lama. Impact kamu bukan dari keramaian, tapi dari depth of work yang kamu tinggalkan.",
    famousPeople: ["Elon Musk", "Nikola Tesla", "Michelle Obama", "Arnold Schwarzenegger"],
  },

  INTP: {
    type: "INTP",
    squad: "Visionary",
    squadColor: "#7C3AED",
    nickname: "Si Pemikir Abadi",
    nicknameEn: "The Logician",
    emoji: "🔬",
    tagline: "Bertanya sampai menemukan kebenaran yang paling dalam",
    description: "Pikiranmu seperti laboratorium yang tidak pernah tutup. Kamu menemukan keindahan dalam ide, pola, dan sistem. Dunia kamu penuh dengan 'bagaimana jika' dan 'mengapa' — dan kamu tidak akan berhenti sampai dapat jawabannya.",
    strengths: ["Analytical thinking mendalam", "Kreativitas dalam problem-solving", "Objektif dan tidak bias", "Open-minded terhadap ide baru", "Passion dalam belajar"],
    weaknesses: ["Procrastination kronis", "Sulit membuat keputusan final", "Detached dari realitas praktis", "Sering meragukan diri sendiri", "Sulit ekspresi emosi"],
    emotionalIntelligence: "Kamu memproses emosi sebagai data yang harus dianalisis. Ini membuat kamu bingung dengan perasaan yang 'tidak logis'. Blind spot: kamu bisa terlalu dalam pikiran sehingga orang di sekitar kamu merasa tidak diperhatikan.",
    selfLoveGuidance: "INTP, kamu sangat keras pada diri sendiri ketika ide kamu tidak sempurna. Remember: done is better than perfect. Self-love kamu dimulai dari action — mulai, selesaikan, lanjut. Thoughts tanpa action is just noise.",
    shadowWork: "Shadow INTP: rasa takut dianggap tidak cerdas, imposter syndrome yang brutal, dan kecenderungan untuk isolate diri ketika overwhelmed. Acknowledge: tidak semua masalah bisa diselesaikan dengan logika.",
    coreValues: ["Kebenaran", "Kebebasan intelektual", "Otonomi", "Inovasi", "Ketepatan"],
    loveLanguage: ["Intellectual stimulation", "Acts of service", "Quality time (dengan orang yang 'get' kamu)"],
    careerPaths: ["Software Engineer / Developer", "Matematikawan / Fisikawan", "Philosopher / Penulis", "Game Designer", "Research Scientist", "Systems Analyst"],
    romanticStyle: "Kamu butuh partner yang bisa merangsang pikiranmu secara intelektual. Kamu bukan romantic dalam cara konvensional — tapi loyal dan thoughtful dalam cara kamu sendiri.",
    socialDynamics: "Kamu mungkin terlihat absent-minded atau tidak tertarik, padahal kamu sangat engaged di dalam. Small talk tidak cocok — kamu butuh deep conversation.",
    purpose: "Kamu hadir untuk menemukan, memahami, dan menjelaskan hal-hal yang orang lain tidak bisa. Calling kamu adalah illuminating the unknown.",
    famousPeople: ["Albert Einstein", "Bill Gates", "Charles Darwin", "Abraham Lincoln"],
  },

  ENTJ: {
    type: "ENTJ",
    squad: "Visionary",
    squadColor: "#7C3AED",
    nickname: "Si Komandan Visi",
    nicknameEn: "The Commander",
    emoji: "👑",
    tagline: "Memimpin bukan pilihan, itu panggilan jiwa",
    description: "Kamu lahir untuk memimpin. Kamu melihat potensi di mana orang lain melihat rintangan, dan kamu tidak akan berhenti sampai visi itu terwujud. Energy kamu menginspirasi — tapi juga bisa mengintimidasi.",
    strengths: ["Leadership natural yang kuat", "Visi jangka panjang yang tajam", "Kemampuan eksekusi tinggi", "Confident dan decisive", "Strategic dalam segala hal"],
    weaknesses: ["Bisa terlalu dominan", "Impatient dengan yang lebih lambat", "Kurang empati dalam push mode", "Workaholism", "Sulit menerima kelemahan"],
    emotionalIntelligence: "Kamu cenderung minimize emosi karena dianggap tidak efisien. Tapi emosi adalah data penting — mengabaikannya membuat kamu miss crucial human factors dalam leadership.",
    selfLoveGuidance: "ENTJ, kamu mendefinisikan diri dari achievement. Tapi siapa kamu ketika tidak ada yang bisa kamu 'accomplish'? Self-love kamu adalah belajar bahwa worth kamu bukan dari produktivitas.",
    shadowWork: "Shadow ENTJ: fear of failure yang disembunyikan di balik confidence, intoleransi terhadap kelemahan diri, dan tendency untuk bulldoze perasaan orang demi goal.",
    coreValues: ["Kompetensi", "Efisiensi", "Pencapaian", "Kepemimpinan", "Visi"],
    loveLanguage: ["Quality time (focused dan productive)", "Acts of service", "Words of affirmation (achievement-based)"],
    careerPaths: ["CEO / Founder", "Pengacara / Jaksa", "Military Officer", "Management Consultant", "Investment Banker", "Politician"],
    romanticStyle: "Kamu intense dan protective sebagai partner. Kamu butuh seseorang yang equally ambitious dan tidak mudah terintimidasi oleh energy kamu.",
    socialDynamics: "Kamu natural center of attention dan connector. Orang tertarik pada confidence kamu — tapi kamu perlu belajar bahwa not everyone moves at your pace.",
    purpose: "Kamu hadir untuk membangun empire — bukan dari ego, tapi dari desire untuk create something meaningful yang outlast kamu.",
    famousPeople: ["Steve Jobs", "Gordon Ramsay", "Napoleon Bonaparte", "Margaret Thatcher"],
  },

  ENTP: {
    type: "ENTP",
    squad: "Visionary",
    squadColor: "#7C3AED",
    nickname: "Si Debater Cemerlang",
    nicknameEn: "The Debater",
    emoji: "🎭",
    tagline: "Menantang status quo dengan senyum di wajah",
    description: "Pikiranmu bergerak lebih cepat dari mulutmu — dan mulutmu sudah sangat cepat. Kamu menemukan kesenangan dalam melawan arus, bukan karena nakal, tapi karena kamu genuinely melihat possibilities yang orang lain lewatkan.",
    strengths: ["Quick-witted dan brilliant", "Adaptive dan creative", "Excellent debater", "Visioner yang innovative", "Charismatic dan persuasif"],
    weaknesses: ["Sulit follow-through", "Bisa argumentative berlebihan", "Boredom yang cepat", "Insensitif terhadap perasaan", "Rebellious tanpa arah"],
    emotionalIntelligence: "Kamu sering menggunakan humor dan debate untuk menghindari vulnerability. Saat kamu berhenti sejenak dari pikiran yang berpacu, kamu akan menemukan ada banyak perasaan yang belum diproses.",
    selfLoveGuidance: "ENTP, kamu takut boring — termasuk boring dengan diri sendiri. Self-love kamu dimulai dari sitting with yourself tanpa distraksi. Temukan siapa kamu ketika tidak ada audience.",
    shadowWork: "Shadow ENTP: fear of commitment karena takut kehilangan freedom, using intellect to avoid intimacy, dan scatter energy ke banyak hal sehingga tidak ada yang matang.",
    coreValues: ["Kebebasan", "Inovasi", "Kecerdasan", "Debate", "Orisinalitas"],
    loveLanguage: ["Intellectual banter", "Quality time (engaging dan spontan)", "Acts of service (yang thoughtful)"],
    careerPaths: ["Entrepreneur", "Pengacara / Mediator", "Stand-up Comedian", "Marketing / Creative Director", "Journalist", "Inventor / Engineer"],
    romanticStyle: "Kamu flirtatious dan charming, tapi commitment butuh waktu. Partner yang cocok: yang bisa keep up dengan pikiran kamu dan tidak insecure dengan debating style kamu.",
    socialDynamics: "Kamu hidup di social situations. Kamu bisa connect dengan hampir siapa saja — tapi deep friendship kamu riservasi untuk yang truly 'get' kamu.",
    purpose: "Kamu hadir untuk challenge cara lama berpikir dan membuka pintu ke possibilities baru. Kamu adalah katalis perubahan.",
    famousPeople: ["Mark Twain", "Tom Hanks", "Celine Dion", "Barack Obama (debating style)"],
  },

  INFJ: {
    type: "INFJ",
    squad: "Harmonizer",
    squadColor: "#EC4899",
    nickname: "Si Dukun Jiwa",
    nicknameEn: "The Advocate",
    emoji: "🔮",
    tagline: "Melihat jiwa orang lain lebih jelas dari cermin mereka sendiri",
    description: "Kamu adalah tipe kepribadian yang paling langka. Di balik ketenangan dan empati kamu yang dalam, ada keteguhan baja. Kamu melihat patterns yang orang lain tidak lihat, dan kamu merasakan dunia dengan intensitas yang sering melelahkan.",
    strengths: ["Empati mendalam", "Intuisi yang tajam", "Komitmen pada nilai-nilai", "Visioner dengan purpose", "Kemampuan healing alami"],
    weaknesses: ["Perfectionism yang melelahkan", "Terlalu sensitif", "Burnout dari absorb emosi orang", "Sulit menetapkan boundaries", "Idealism yang tidak realistis"],
    emotionalIntelligence: "Kamu sangat in-tune dengan emosi orang lain sampai sering tidak tahu mana perasaan kamu dan mana yang kamu absorb dari orang lain. Ini adalah gift sekaligus burden.",
    selfLoveGuidance: "INFJ, kamu memberi terlalu banyak pada orang lain sampai empty. Self-love kamu dimulai dari understanding bahwa kamu tidak bisa pour from an empty cup. Boundaries bukan egoisme — itu self-preservation.",
    shadowWork: "Shadow INFJ: door-slamming yang tiba-tiba, memendam perasaan sampai meledak, dan tendency untuk sacrifice diri sendiri demi ideal yang tidak sustainable.",
    coreValues: ["Autentisitas", "Purpose", "Pertumbuhan", "Integritas", "Dampak positif"],
    loveLanguage: ["Quality time (deep dan meaningful)", "Words of affirmation", "Physical touch (dalam safe relationship)"],
    careerPaths: ["Psikolog / Konselor", "Penulis / Poet", "Guru / Mentor", "Non-profit Leader", "Healthcare Worker", "Spiritual Guide"],
    romanticStyle: "Kamu all-in dan intensely devoted. Kamu mencari soulmate, bukan sekedar partner. Butuh waktu lama untuk open up — tapi ketika sudah, kamu adalah partner yang extraordinarily thoughtful.",
    socialDynamics: "Kamu tampak extroverted tapi sebenarnya deeply introverted. Kamu perlu solitude untuk recharge. Social interactions yang tidak meaningful menguras energy kamu.",
    purpose: "Kamu hadir untuk heal, guide, dan inspire. Ada calling yang lebih besar dari dirimu — dan kamu sudah merasakannya sejak kecil.",
    famousPeople: ["Martin Luther King Jr.", "Nelson Mandela", "Lady Gaga", "Oprah Winfrey"],
  },

  INFP: {
    type: "INFP",
    squad: "Harmonizer",
    squadColor: "#EC4899",
    nickname: "Si Idealis Dalam",
    nicknameEn: "The Mediator",
    emoji: "🌙",
    tagline: "Hidup di dunia yang lebih indah dari yang kebanyakan orang lihat",
    description: "Kamu membawa kedalaman yang luar biasa. Di dalam dirimu ada dunia yang kaya — penuh empati, kreativitas, dan idealisme. Kamu mungkin terlihat pendiam, tapi di dalam ada universe yang sedang berputar.",
    strengths: ["Empati yang dalam", "Kreativitas yang autentik", "Passion pada values", "Healing presence", "Imagination yang kaya"],
    weaknesses: ["Self-critical yang brutal", "Idealism yang bisa menyakiti", "Avoidance dari konflik", "Overthinking emosi", "Sulit move on"],
    emotionalIntelligence: "Kamu merasakan emosi dengan intensitas tinggi. Ini membuat kamu extraordinarily empathetic — tapi juga vulnerable terhadap emotional overwhelm. Kamu butuh outlets kreatif untuk proses itu.",
    selfLoveGuidance: "INFP, inner critic kamu adalah yang paling keras. Kamu memegang diri pada standar yang tidak kamu terapkan pada orang lain. Coba ini: perlakukan dirimu seperti kamu memperlakukan best friend kamu.",
    shadowWork: "Shadow INFP: self-victimization, escapism dari realita melalui fantasy, dan resentment yang dipendam karena tidak mau konfrontasi.",
    coreValues: ["Autentisitas", "Kreativitas", "Kebebasan", "Pertumbuhan personal", "Kasih sayang"],
    loveLanguage: ["Words of affirmation", "Quality time (intimate dan meaningful)", "Acts of service (yang thoughtful)"],
    careerPaths: ["Penulis / Novelis", "Psikolog / Art Therapist", "Musisi / Seniman", "Social Worker", "Educator", "Activist"],
    romanticStyle: "Kamu romantic dan devoted. Kamu mencintai dengan intensitas yang kadang membuat orang lain kewalahan. Kamu butuh partner yang menghargai depth dan tidak takut dengan vulnerability.",
    socialDynamics: "Kamu lebih nyaman dengan satu atau dua orang yang kamu trust daripada grup besar. Kamu genuine dan hate superficiality.",
    purpose: "Kamu hadir untuk mengekspresikan kebenaran yang dalam melalui seni, empati, dan nilai-nilai yang kamu pegang. Suara kamu penting.",
    famousPeople: ["J.R.R. Tolkien", "William Shakespeare", "Princess Diana", "John Lennon"],
  },

  ENFJ: {
    type: "ENFJ",
    squad: "Harmonizer",
    squadColor: "#EC4899",
    nickname: "Si Pemimpin Hati",
    nicknameEn: "The Protagonist",
    emoji: "💫",
    tagline: "Menyalakan api potensi dalam diri setiap orang",
    description: "Kamu adalah pemimpin yang memimpin dengan hati. Kamu melihat potensi terbaik dalam setiap orang — bahkan sebelum mereka melihatnya sendiri. Energy kamu menginspirasi dan presence kamu menghangatkan.",
    strengths: ["Charisma dan influence alami", "Empati yang genuine", "Kemampuan motivasi tinggi", "Organized dan goal-oriented", "Excellent communicator"],
    weaknesses: ["Terlalu berfokus pada orang lain", "Sensitif terhadap konflik", "Approval-seeking", "Overextend diri", "Sulit menetapkan boundaries"],
    emotionalIntelligence: "Kamu highly attuned dengan emosi orang lain. Tantangan kamu: memastikan kamu juga mendengarkan emosi dirimu sendiri, bukan hanya menjadi container untuk orang lain.",
    selfLoveGuidance: "ENFJ, kamu sering menaruh kebahagiaan orang lain sebelum dirimu sendiri. Self-love kamu adalah belajar bahwa caring untuk dirimu bukan berarti tidak peduli pada orang lain.",
    shadowWork: "Shadow ENFJ: manipulation halus untuk get desired outcomes, resentment ketika usaha tidak diapresiasi, dan identity yang terlalu terikat pada 'the helper'.",
    coreValues: ["Koneksi", "Pertumbuhan", "Harmoni", "Service", "Autentisitas"],
    loveLanguage: ["Words of affirmation", "Quality time", "Physical touch"],
    careerPaths: ["Guru / Profesor", "Counselor / Life Coach", "HR Manager", "Non-profit Director", "Actor / Public Speaker", "Diplomat"],
    romanticStyle: "Kamu devoted dan attentive partner. Kamu cenderung prioritize partner's needs. Butuh partner yang equally expressive dan tidak take kamu for granted.",
    socialDynamics: "Kamu magnet sosial yang genuine. Orang merasa didengar dan dihargai di sekitar kamu. Tapi kamu perlu energy untuk recharge.",
    purpose: "Kamu hadir untuk uplift dan transform orang-orang di sekitar kamu. Legacy kamu hidup dalam orang-orang yang kamu inspire.",
    famousPeople: ["Barack Obama", "Oprah Winfrey", "Jennifer Lawrence", "Martin Luther King Jr."],
  },

  ENFP: {
    type: "ENFP",
    squad: "Harmonizer",
    squadColor: "#EC4899",
    nickname: "Si Penyemarak Alam",
    nicknameEn: "The Campaigner",
    emoji: "🌈",
    tagline: "Melihat keajaiban di setiap sudut yang orang lain lewatkan",
    description: "Kamu adalah burst of energy yang contagious. Kamu membawa warna ke dunia yang abu-abu. Curiosity kamu tidak ada batasnya dan enthusiasm kamu membuat orang terinfeksi semangat yang sama.",
    strengths: ["Enthusiastic dan infectious", "Kreativitas tinggi", "Empati yang tulus", "Kemampuan koneksi yang luar biasa", "Adaptif dan open-minded"],
    weaknesses: ["Sulit fokus jangka panjang", "Overthinking emosi", "Approval-seeking", "Impulsif", "Sulit dengan rutinitas"],
    emotionalIntelligence: "Kamu sangat aware dengan emosi — kamu dan orang lain. Tapi kamu kadang so caught up dalam excitement sehingga mengabaikan sinyal emosi penting.",
    selfLoveGuidance: "ENFP, kamu sering look for validation eksternal padahal validation yang paling kamu butuhkan ada dari dalam. Belajar trust dirimu sendiri tanpa butuh approval.",
    shadowWork: "Shadow ENFP: escapism dari komitmen, people-pleasing yang draining, dan anxiety mendalam yang disembunyikan di balik cheerfulness.",
    coreValues: ["Kebebasan", "Autentisitas", "Koneksi", "Kreativitas", "Pertumbuhan"],
    loveLanguage: ["Words of affirmation", "Quality time (adventures)", "Physical touch"],
    careerPaths: ["Journalist / Content Creator", "Actor / Performer", "Entrepreneur", "Counselor", "Teacher", "Marketing Creative"],
    romanticStyle: "Kamu romantic, spontan, dan devoted ketika menemukan orang yang right. Kamu butuh partner yang memberikan ruang untuk grow tapi juga grounding presence.",
    socialDynamics: "Kamu thrives di social settings. Kamu natural networker yang genuinely interested dengan semua orang. Tantangan: jangan spread yourself too thin.",
    purpose: "Kamu hadir untuk inspire, connect, dan ignite passion dalam diri orang lain. Dunia lebih berwarna karena kamu ada.",
    famousPeople: ["Robin Williams", "Walt Disney", "Ellen DeGeneres", "Miley Cyrus"],
  },

  ISTJ: {
    type: "ISTJ",
    squad: "Guardian",
    squadColor: "#F59E0B",
    nickname: "Si Tiang Berdiri",
    nicknameEn: "The Logistician",
    emoji: "🏛️",
    tagline: "Ketika orang lain ragu, kamu sudah selesaikan",
    description: "Kamu adalah fondasi yang menopang dunia. Kamu bukan yang paling berisik di ruangan, tapi kamu yang paling bisa diandalkan. Ketika semua orang panik, kamu sudah punya plan.",
    strengths: ["Sangat reliable dan responsible", "Detail-oriented", "Persistence yang luar biasa", "Integritas tinggi", "Practical dan organized"],
    weaknesses: ["Resistant terhadap perubahan", "Terlalu rigid", "Sulit ekspresikan emosi", "Judgmental terhadap yang tidak terstruktur", "Workaholic"],
    emotionalIntelligence: "Kamu lebih comfortable dengan facts daripada feelings. Ini membuat kamu reliable tapi kadang terlihat dingin. Belajar untuk acknowledge emosi tanpa immediately trying to fix atau dismiss.",
    selfLoveGuidance: "ISTJ, kamu mendefinisikan worth dari duty dan productivity. Kamu lupa bahwa kamu berharga bukan karena apa yang kamu lakukan, tapi karena siapa kamu.",
    shadowWork: "Shadow ISTJ: rigidity yang prevents growth, self-neglect karena terlalu fokus pada obligation, dan resentment yang dipendam karena tidak pernah express needs.",
    coreValues: ["Tanggung jawab", "Loyalitas", "Integritas", "Tradisi", "Keandalan"],
    loveLanguage: ["Acts of service", "Quality time (routines yang meaningful)", "Words of affirmation"],
    careerPaths: ["Akuntan / Auditor", "Dokter / Perawat", "Militer / Polisi", "Administrator", "Engineer", "Hakim"],
    romanticStyle: "Kamu partner yang sangat loyal dan dependable. Kamu mungkin tidak yang paling romantic, tapi actions kamu berbicara lebih keras dari kata-kata.",
    socialDynamics: "Kamu prefer small, deep friendships over large social circles. Kamu butuh waktu untuk trust orang baru, tapi ketika sudah, kamu teman yang tak ternilai.",
    purpose: "Kamu hadir untuk menjaga, melindungi, dan memastikan dunia berjalan dengan benar. Kamu adalah backbone of society.",
    famousPeople: ["Angela Merkel", "Warren Buffett", "Vin Diesel", "Natalie Portman"],
  },

  ISFJ: {
    type: "ISFJ",
    squad: "Guardian",
    squadColor: "#F59E0B",
    nickname: "Si Pelindung Lembut",
    nicknameEn: "The Protector",
    emoji: "🛡️",
    tagline: "Cinta yang ditunjukkan lewat perhatian yang tak terlihat",
    description: "Kamu adalah heart of your circle. Kamu ingat detail-detail kecil tentang orang yang kamu sayangi — ulang tahun, makanan favorit, mimpi terdalam mereka. Caring adalah bahasa pertama kamu.",
    strengths: ["Sangat caring dan supportive", "Reliable dan konsisten", "Detail-oriented", "Pratical helper", "Patience yang luar biasa"],
    weaknesses: ["Sulit bilang tidak", "Self-neglect", "Terlalu sensitif terhadap kritik", "Resistant terhadap perubahan", "Invisible effort yang tidak diakui"],
    emotionalIntelligence: "Kamu sangat sensitif dengan emosi orang lain tapi sering tidak mengutamakan emosi kamu sendiri. Kamu perlu belajar bahwa kebutuhan kamu juga valid.",
    selfLoveGuidance: "ISFJ, kamu memberi tanpa batas sampai kamu tidak ada sisa. Self-love kamu adalah belajar receive — menerima bantuan, pujian, dan perhatian tanpa guilty.",
    shadowWork: "Shadow ISFJ: passive-aggressiveness ketika needs tidak terpenuhi, playing martyr, dan resentment yang tersembunyi karena selalu prioritize orang lain.",
    coreValues: ["Harmoni", "Service", "Loyalitas", "Tradisi", "Keluarga"],
    loveLanguage: ["Acts of service", "Quality time", "Words of affirmation"],
    careerPaths: ["Perawat / Dokter", "Guru", "Social Worker", "HR", "Event Organizer", "Interior Designer"],
    romanticStyle: "Kamu partner yang thoughtful, attentive, dan dedicated. Kamu perlu partner yang notice dan appreciate the things you do — bukan take it for granted.",
    socialDynamics: "Kamu prefer meaningful one-on-one connections. Kamu adalah listener yang luar biasa dan people feel safe dengan kamu.",
    purpose: "Kamu hadir untuk nurture dan protect orang-orang di sekitar kamu. Impact kamu adalah di kehidupan sehari-hari yang kamu sentuh dengan kindness.",
    famousPeople: ["Mother Teresa", "Kate Middleton", "Beyoncé", "Rosa Parks"],
  },

  ESTJ: {
    type: "ESTJ",
    squad: "Guardian",
    squadColor: "#F59E0B",
    nickname: "Si Jaga Gerbang",
    nicknameEn: "The Supervisor",
    emoji: "⚖️",
    tagline: "Order bukan pilihan, itu standar minimum",
    description: "Kamu adalah administrator born. Kamu melihat chaos dan langsung tahu bagaimana memperbaikinya. Standards kamu tinggi — untuk dirimu dan orang lain. Kamu pegang erat tradisi dan prove kamu layak melalui hasil.",
    strengths: ["Leadership yang decisive", "Organized dan efisien", "Reliable dan konsisten", "Honest dan direct", "Strong work ethic"],
    weaknesses: ["Infleksibel terhadap ide baru", "Terlalu judgemental", "Kurang sensitif terhadap emosi", "Dominan berlebihan", "Workaholic"],
    emotionalIntelligence: "Kamu cenderung dismiss perasaan yang 'tidak produktif'. Belajar bahwa emotional intelligence adalah leadership skill yang paling underrated.",
    selfLoveGuidance: "ESTJ, kamu identify diri dari status dan achievement. Self-love kamu adalah belajar bahwa kamu tidak perlu constantly prove dirimu kepada siapa pun.",
    shadowWork: "Shadow ESTJ: authoritarian tanpa empati, judging orang yang berbeda cara hidupnya, dan inability to admit when wrong.",
    coreValues: ["Order", "Tanggung jawab", "Efisiensi", "Tradisi", "Integritas"],
    loveLanguage: ["Acts of service", "Words of affirmation", "Quality time (structured)"],
    careerPaths: ["Manager / Direktur", "Pengacara", "Military Officer", "Judge", "Financial Advisor", "Principal"],
    romanticStyle: "Kamu provider dan protector yang kuat. Kamu expressive dalam action, bukan kata-kata. Butuh partner yang menghargai stability.",
    socialDynamics: "Kamu natural leader dalam grup. Kamu pegang nilai-nilai komunitas dengan kuat. Belajar bahwa tidak semua orang perlu ikut cara kamu.",
    purpose: "Kamu hadir untuk membangun dan memelihara struktur yang membuat masyarakat berfungsi. Kamu adalah pillar of community.",
    famousPeople: ["Michelle Obama", "Frank Sinatra", "Sonia Sotomayor", "Judge Judy"],
  },

  ESFJ: {
    type: "ESFJ",
    squad: "Guardian",
    squadColor: "#F59E0B",
    nickname: "Si Konselor Hati",
    nicknameEn: "The Provider",
    emoji: "🤝",
    tagline: "Kebahagiaan orang-orang yang kamu cintai adalah kebahagiaanmu",
    description: "Kamu adalah social glue dalam setiap lingkaran. Kamu yang ingat semua orang, yang organize gathering, yang pastikan semua merasa included. Warmth kamu genuine dan orang merasakannya.",
    strengths: ["Warm dan nurturing", "Excellent communicator", "Organized dan reliable", "Loyal dan dedicated", "Practical helper"],
    weaknesses: ["Terlalu butuh approval", "Sensitive terhadap kritik", "Gossip tendency", "Infleksibel terhadap yang berbeda", "Sulit handle konflik"],
    emotionalIntelligence: "Kamu sangat aware dengan social dynamics dan perasaan orang lain. Tantangan: jangan let desire for harmony prevent honest conversations.",
    selfLoveGuidance: "ESFJ, kamu sangat butuh validation eksternal. Self-love kamu dimulai dari belajar bahwa pendapat orang lain tentang kamu bukan definisi kamu.",
    shadowWork: "Shadow ESFJ: using generosity to control, gossip sebagai way to connect, dan losing self dalam effort to please everyone.",
    coreValues: ["Harmoni", "Loyalitas", "Service", "Komunitas", "Tradisi"],
    loveLanguage: ["Words of affirmation", "Acts of service", "Quality time"],
    careerPaths: ["Teacher", "Nurse", "Social Worker", "Event Planner", "Sales", "Public Relations"],
    romanticStyle: "Kamu devoted dan expressive partner. Kamu butuh partner yang verbally appreciative dan participates dalam building a life bersama.",
    socialDynamics: "Kamu thrives dalam komunitas. Kamu natural organizer dan people love being around kamu karena kamu make everyone feel welcome.",
    purpose: "Kamu hadir untuk create belonging dan nurture community. Kamu adalah heart yang menghubungkan.",
    famousPeople: ["Taylor Swift", "Jennifer Garner", "Steve Harvey", "Prince William"],
  },

  ISTP: {
    type: "ISTP",
    squad: "Explorer",
    squadColor: "#3B82F6",
    nickname: "Si Ahli Logika",
    nicknameEn: "The Craftsman",
    emoji: "🔧",
    tagline: "Mengerti cara kerja dunia dengan menyentuh, bukan membaca",
    description: "Kamu adalah problem-solver yang cool under pressure. Kamu lebih suka action daripada kata-kata, dan tangan kamu lebih fasih dari lidah kamu. Kamu bisa fix apa saja — dari mesin sampai situasi yang rumit.",
    strengths: ["Calm dalam krisis", "Hands-on dan practical", "Independent dan self-sufficient", "Observant dan analytical", "Adaptable"],
    weaknesses: ["Kurang ekspresif emosi", "Commitment-phobic", "Impulsif dalam keputusan besar", "Bisa terlihat apathetic", "Sulit long-term planning"],
    emotionalIntelligence: "Kamu process emosi secara private dan sering tidak show them. Ini bisa membuat orang sekitar kamu merasa kamu tidak peduli, padahal kamu peduli dengan cara kamu sendiri.",
    selfLoveGuidance: "ISTP, kamu sangat independent sehingga kadang isolate diri. Self-love kamu adalah belajar bahwa minta bantuan atau support bukan kelemahan.",
    shadowWork: "Shadow ISTP: extreme detachment sebagai defense mechanism, recklessness yang menyamar sebagai freedom, dan inability to commit karena fear of losing independence.",
    coreValues: ["Kebebasan", "Efisiensi", "Kemandirian", "Mastery", "Pragmatisme"],
    loveLanguage: ["Acts of service", "Quality time (shared activities)", "Physical touch"],
    careerPaths: ["Engineer / Mekanik", "Pilot / Surgeon", "Software Developer", "Forensic Scientist", "Entrepreneur", "Chef"],
    romanticStyle: "Kamu partner yang observant dan practical. Kamu show love through actions. Butuh partner yang tidak clingy dan respects your space.",
    socialDynamics: "Kamu observer yang quiet dalam grup. Kamu bukan yang paling vocal tapi sering yang paling insightful ketika kamu berbicara.",
    purpose: "Kamu hadir untuk solve masalah yang orang lain tidak bisa. Hands kamu adalah alat untuk change dunia menjadi lebih functional.",
    famousPeople: ["Clint Eastwood", "Michael Jordan", "Bruce Lee", "Bear Grylls"],
  },

  ISFP: {
    type: "ISFP",
    squad: "Explorer",
    squadColor: "#3B82F6",
    nickname: "Si Seniman Jiwa",
    nicknameEn: "The Composer",
    emoji: "🎨",
    tagline: "Hidup adalah kanvas dan kamu sedang melukis",
    description: "Kamu adalah jiwa yang tenang dengan passion yang dalam. Kamu tidak banyak bicara tentang dirimu, tapi ekspresi kamu — melalui seni, tindakan, atau cara kamu ada di dunia — berbicara lebih dari kata-kata.",
    strengths: ["Artistic dan creative", "Empati yang gentle", "Adaptable dan open", "Passionate terhadap values", "Present-moment awareness"],
    weaknesses: ["Avoidant terhadap konflik", "Overly private", "Self-critical diam-diam", "Sulit long-term planning", "Sensitive terhadap criticism"],
    emotionalIntelligence: "Kamu merasakan emosi sangat dalam tapi jarang mengekspresikannya secara verbal. Kamu lebih ekspresif melalui kreativitas dan tindakan.",
    selfLoveGuidance: "ISFP, kamu sering meragukan worth kamu sendiri diam-diam. Self-love kamu adalah belajar bahwa kamu tidak perlu prove anything — eksistensimu sendiri sudah berharga.",
    shadowWork: "Shadow ISFP: avoidance dari semua hal yang uncomfortable termasuk necessary confrontations, self-neglect karena terlalu absorbed dalam experience orang lain.",
    coreValues: ["Kebebasan", "Autentisitas", "Keindahan", "Harmoni", "Kreativitas"],
    loveLanguage: ["Physical touch", "Quality time", "Acts of service"],
    careerPaths: ["Seniman / Desainer", "Musisi", "Fotografer", "Physical Therapist", "Veterinarian", "Chef"],
    romanticStyle: "Kamu gentle, sensitive, dan deeply loyal. Kamu show love through small but meaningful gestures. Butuh partner yang patient dan appreciates subtlety.",
    socialDynamics: "Kamu lebih comfortable dalam setting kecil. Kamu observer yang gentle dan people feel at ease dengan kamu.",
    purpose: "Kamu hadir untuk menambah keindahan dan kedalaman ke dunia melalui cara unik kamu mengekspresikan diri.",
    famousPeople: ["Michael Jackson", "Lana Del Rey", "David Beckham", "Frida Kahlo"],
  },

  ESTP: {
    type: "ESTP",
    squad: "Explorer",
    squadColor: "#3B82F6",
    nickname: "Si Diraja Aksi",
    nicknameEn: "The Entrepreneur",
    emoji: "🔥",
    tagline: "Hidup terlalu singkat untuk tidak mencoba",
    description: "Kamu adalah action embodied. Kamu tidak mikir terlalu panjang — kamu action dan figure it out on the way. Kamu hidup di present moment dengan intensitas yang membuat orang lain pusing tapi excited.",
    strengths: ["Bold dan decisive", "Energetic dan charismatic", "Crisis handling terbaik", "Adaptable dan resourceful", "Perceptive terhadap orang"],
    weaknesses: ["Impulsif berlebihan", "Risk-taking tanpa perhitungan", "Bored dengan routine", "Insensitif terhadap perasaan", "Short-term thinking"],
    emotionalIntelligence: "Kamu tangkap social cues dengan cepat dan can read people well. Tapi kamu sering pindah terlalu cepat untuk process emosi kamu sendiri secara dalam.",
    selfLoveGuidance: "ESTP, kamu escape dari uncomfortable feelings dengan action dan excitement. Self-love kamu adalah belajar sit with discomfort tanpa lari.",
    shadowWork: "Shadow ESTP: recklessness yang menyakiti orang lain, superficiality sebagai armor, dan inability untuk slow down dan be vulnerable.",
    coreValues: ["Kebebasan", "Aksi", "Pragmatisme", "Fun", "Petualangan"],
    loveLanguage: ["Physical touch", "Quality time (adventure)", "Acts of service"],
    careerPaths: ["Entrepreneur", "Sales / Marketing", "Emergency Responder", "Atlet", "Actor", "Financial Trader"],
    romanticStyle: "Kamu exciting dan attentive partner yang present. Kamu butuh partner yang tidak needy dan can keep up dengan energy kamu.",
    socialDynamics: "Kamu natural center of attention bukan karena trying to be, tapi karena energy kamu genuinely engaging. Kamu bisa work any room.",
    purpose: "Kamu hadir untuk demonstrate bahwa hidup itu untuk dijalani, bukan ditonton. Kamu adalah spark yang mendorong orang untuk take chances.",
    famousPeople: ["Donald Trump", "Eddie Murphy", "Madonna", "Jack Nicholson"],
  },

  ESFP: {
    type: "ESFP",
    squad: "Explorer",
    squadColor: "#3B82F6",
    nickname: "Si Perayanya Hidup",
    nicknameEn: "The Entertainer",
    emoji: "🎉",
    tagline: "Setiap momen adalah alasan untuk celebrate",
    description: "Kamu adalah sunshine dalam bentuk manusia. Kamu hadir dan semua orang instantly merasa lebih hidup. Kamu tidak perform untuk disukai — kamu genuinely enjoy life dan itu menular.",
    strengths: ["Charismatic dan joyful", "Spontan dan adventurous", "Empathetic dan caring", "Excellent at making people feel included", "Adaptable dan practical"],
    weaknesses: ["Impulsif dalam keputusan", "Avoidant dari hal serius", "Sensitive terhadap kritik", "Bored dengan long-term planning", "People-pleasing"],
    emotionalIntelligence: "Kamu sangat attuned dengan emotional atmosphere di ruangan. Kamu natural mood-lifter. Tantangan: kamu kadang avoid negative emotions dengan distract diri dengan fun.",
    selfLoveGuidance: "ESFP, kamu sering define worth dari seberapa banyak orang tertawa atau senang karena kamu. Self-love kamu adalah belajar bahwa kamu berharga bahkan ketika diam dan tidak entertaining.",
    shadowWork: "Shadow ESFP: avoid necessary hard conversations, emotional immaturity di bawah cheerfulness, dan fear of being alone dengan diri sendiri.",
    coreValues: ["Kesenangan", "Koneksi", "Freedom", "Experience", "Kasih sayang"],
    loveLanguage: ["Physical touch", "Words of affirmation", "Quality time (fun experiences)"],
    careerPaths: ["Performer / Actor", "Event Planner", "Teacher (creative)", "Healthcare", "Sales", "Chef"],
    romanticStyle: "Kamu affectionate, fun, dan generous partner. Kamu butuh partner yang not too serious dan appreciates spontaneity.",
    socialDynamics: "Kamu thrive dalam group settings dan adalah natural entertainer. Kamu make sure no one feels left out.",
    purpose: "Kamu hadir untuk remind orang bahwa joy adalah birthright, bukan hadiah. Kamu adalah living proof bahwa hidup bisa indah.",
    famousPeople: ["Adele", "Will Smith", "Marilyn Monroe", "Lizzo"],
  },
};

export const getSquadColor = (squad: Squad): string => {
  const colors: Record<Squad, string> = {
    Explorer: "#3B82F6",
    Guardian: "#F59E0B",
    Visionary: "#7C3AED",
    Harmonizer: "#EC4899",
  };
  return colors[squad];
};

export const getSquadEmoji = (squad: Squad): string => {
  const emojis: Record<Squad, string> = {
    Explorer: "🚀",
    Guardian: "🛡️",
    Visionary: "⚡",
    Harmonizer: "🌟",
  };
  return emojis[squad];
};
