export type Dimension = "EI" | "SN" | "TF" | "JP";

export interface Question {
  id: number;
  dimension: Dimension;
  text: string;
  scenario?: string;
  optionA: { text: string; weight: "strong_a" | "slight_a" | "neutral" | "slight_b" | "strong_b" };
  optionB: { text: string; weight: "strong_a" | "slight_a" | "neutral" | "slight_b" | "strong_b" };
  labelA: string; // E/S/T/J
  labelB: string; // I/N/F/P
}

// Scoring guide:
// strong_a  = +3 to labelA
// slight_a  = +1 to labelA
// neutral   = 0
// slight_b  = +1 to labelB
// strong_b  = +3 to labelB

export const QUESTIONS: Question[] = [
  // ===== E/I DIMENSION (25 questions) =====
  {
    id: 1,
    dimension: "EI",
    text: "Setelah seharian yang panjang, apa yang paling kamu inginkan?",
    optionA: { text: "Ngobrol dan hangout bareng teman-teman — itu yang isi energi kamu", weight: "strong_a" },
    optionB: { text: "Sendirian di rumah, scroll atau nonton — kamu butuh quiet time", weight: "strong_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 2,
    dimension: "EI",
    text: "Di pesta yang kamu tidak kenal banyak orang...",
    optionA: { text: "Kamu excited! Peluang ketemu orang baru yang seru", weight: "strong_a" },
    optionB: { text: "Kamu survive, tapi drain banget — lebih suka acara yang sudah kenal semua", weight: "strong_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 3,
    dimension: "EI",
    text: "Kalau lagi ada masalah besar, kamu cenderung...",
    optionA: { text: "Cerita ke teman atau orang terdekat — talking it out helps", weight: "slight_a" },
    optionB: { text: "Proses sendiri dulu sampai jelas, baru mungkin cerita", weight: "slight_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 4,
    dimension: "EI",
    scenario: "Bayangkan kamu punya weekend kosong total.",
    text: "Yang pertama kamu pikirkan adalah...",
    optionA: { text: "Ajak teman-teman untuk plan sesuatu bersama", weight: "strong_a" },
    optionB: { text: "Finally! Waktu untuk diri sendiri tanpa gangguan", weight: "strong_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 5,
    dimension: "EI",
    text: "Saat bekerja atau belajar, kamu lebih produktif...",
    optionA: { text: "Di tempat ramai — ada energy orang lain yang bikin semangat", weight: "slight_a" },
    optionB: { text: "Di tempat tenang dan sepi — bisa fokus lebih dalam", weight: "strong_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 6,
    dimension: "EI",
    text: "Orang-orang yang baru kenal kamu biasanya bilang kamu...",
    optionA: { text: "Mudah diajak ngobrol dan terbuka", weight: "slight_a" },
    optionB: { text: "Pendiam atau perlu waktu untuk kenal lebih dalam", weight: "slight_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 7,
    dimension: "EI",
    text: "Dalam meeting atau diskusi grup...",
    optionA: { text: "Kamu aktif speak up — ide mengalir lebih baik ketika dibicarakan", weight: "strong_a" },
    optionB: { text: "Kamu lebih banyak dengarkan dan proses, speak up kalau ada yang worth sharing", weight: "slight_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 8,
    dimension: "EI",
    scenario: "Kamu baru selesai presentasi besar yang sukses.",
    text: "Cara kamu celebrate...",
    optionA: { text: "Langsung ajak tim atau teman makan-makan dan rayakan bersama", weight: "strong_a" },
    optionB: { text: "Pulang ke rumah, me-time, refleksi sejenak", weight: "strong_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 9,
    dimension: "EI",
    text: "Seberapa sering kamu merasa 'capek secara sosial' setelah banyak interaksi?",
    optionA: { text: "Jarang — interaksi justru bikin kamu charged up", weight: "strong_a" },
    optionB: { text: "Sering — kamu butuh recovery time setelah banyak socialization", weight: "strong_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 10,
    dimension: "EI",
    text: "Kalau mau ambil keputusan penting, kamu lebih suka...",
    optionA: { text: "Diskusi sama banyak orang, dapat berbagai perspektif", weight: "slight_a" },
    optionB: { text: "Merenung sendiri, sortir pikiran sebelum minta input orang", weight: "slight_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 11,
    dimension: "EI",
    text: "Kamu punya teman lebih banyak atau lebih sedikit dari rata-rata orang?",
    optionA: { text: "Lebih banyak — kamu suka punya lingkaran luas", weight: "strong_a" },
    optionB: { text: "Lebih sedikit, tapi lebih dalam — quality over quantity", weight: "strong_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 12,
    dimension: "EI",
    scenario: "Kamu naik taksi online dan driver-nya ajak ngobrol.",
    text: "Reaksi kamu...",
    optionA: { text: "Seru dong! Kamu balas dan enjoy the conversation", weight: "strong_a" },
    optionB: { text: "Kamu sopan balas, tapi dalam hati pengen duduk diam aja", weight: "strong_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 13,
    dimension: "EI",
    text: "Kamu lebih sering merasa...",
    optionA: { text: "Bosan atau restless kalau terlalu banyak waktu sendirian", weight: "strong_a" },
    optionB: { text: "Overwhelmed atau drained kalau terlalu banyak waktu dengan orang", weight: "strong_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 14,
    dimension: "EI",
    text: "Cara kamu paling enjoy belajar hal baru...",
    optionA: { text: "Workshop, diskusi grup, atau belajar bareng teman", weight: "slight_a" },
    optionB: { text: "Baca, research sendiri, atau online course yang bisa dikerjakan sendiri", weight: "slight_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 15,
    dimension: "EI",
    text: "Saat kamu excited tentang sesuatu...",
    optionA: { text: "Kamu langsung share ke siapa saja yang mau dengarkan", weight: "strong_a" },
    optionB: { text: "Kamu simpan dulu untuk diri sendiri atau share ke satu-dua orang terpilih", weight: "strong_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 16,
    dimension: "EI",
    text: "Di tempat kerja baru, kamu biasanya...",
    optionA: { text: "Aktif introduce diri dan cepat build relationships", weight: "strong_a" },
    optionB: { text: "Observe dulu beberapa waktu sebelum benar-benar open up", weight: "strong_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 17,
    dimension: "EI",
    text: "Silences dalam percakapan terasa...",
    optionA: { text: "Awkward — kamu biasanya yang isi silence itu", weight: "slight_a" },
    optionB: { text: "Comfortable — kamu tidak perlu selalu ngisi setiap ruang diam", weight: "slight_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 18,
    dimension: "EI",
    scenario: "Kamu pindah ke kota baru sendirian.",
    text: "Yang pertama kamu prioritaskan...",
    optionA: { text: "Find activities dan places untuk meet people ASAP", weight: "strong_a" },
    optionB: { text: "Set up comfortable space untuk dirimu sendiri dulu", weight: "strong_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 19,
    dimension: "EI",
    text: "Saat kamu punya ide baru, kamu lebih suka...",
    optionA: { text: "Brainstorm bareng orang lain — ide makin berkembang", weight: "slight_a" },
    optionB: { text: "Pikirkan sendiri sampai matang baru share", weight: "slight_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 20,
    dimension: "EI",
    text: "Orang-orang close ke kamu bilang kamu adalah...",
    optionA: { text: "Selalu ada dan aktif dalam kehidupan sosial", weight: "strong_a" },
    optionB: { text: "Perlu di-reach out dulu, tidak selalu yang inisiatif", weight: "strong_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 21,
    dimension: "EI",
    text: "Lunch break paling ideal kamu adalah...",
    optionA: { text: "Makan bareng teman-teman sambil ngobrol santai", weight: "slight_a" },
    optionB: { text: "Makan sendiri atau scroll HP — recharge solo time", weight: "slight_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 22,
    dimension: "EI",
    text: "Saat kamu bosan, kamu biasanya...",
    optionA: { text: "Hubungi seseorang untuk hangout atau chat", weight: "strong_a" },
    optionB: { text: "Cari aktivitas solo — buku, game, hobby sendiri", weight: "strong_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 23,
    dimension: "EI",
    text: "Dalam situasi konflik, kamu cenderung...",
    optionA: { text: "Langsung address dan bicarakan secepat mungkin", weight: "slight_a" },
    optionB: { text: "Butuh waktu sendiri dulu untuk cooling down sebelum bicara", weight: "slight_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 24,
    dimension: "EI",
    text: "Phone call mendadak dari orang yang tidak terlalu dekat terasa...",
    optionA: { text: "Fine, kamu happy untuk ngobrol kapan saja", weight: "strong_a" },
    optionB: { text: "Sedikit jarring — kamu prefer teks dulu atau tahu ada phone call yang akan datang", weight: "strong_b" },
    labelA: "E",
    labelB: "I",
  },
  {
    id: 25,
    dimension: "EI",
    text: "Dari semua ini, mana yang paling describes kamu?",
    optionA: { text: "Orang mengenal kamu karena energy dan kehadiranmu yang kuat", weight: "strong_a" },
    optionB: { text: "Orang mengenal kamu karena depth dan thoughtfulness kamu", weight: "strong_b" },
    labelA: "E",
    labelB: "I",
  },

  // ===== S/N DIMENSION (25 questions) =====
  {
    id: 26,
    dimension: "SN",
    text: "Saat menghadapi masalah baru, kamu lebih percaya pada...",
    optionA: { text: "Pengalaman dan fakta yang terbukti — tried and true works", weight: "strong_a" },
    optionB: { text: "Intuisi dan pattern yang kamu rasa dari dalam", weight: "strong_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 27,
    dimension: "SN",
    text: "Kamu lebih tertarik dengan...",
    optionA: { text: "Bagaimana sesuatu bekerja secara konkret dan praktis", weight: "strong_a" },
    optionB: { text: "Mengapa sesuatu ada dan apa maknanya secara lebih dalam", weight: "strong_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 28,
    dimension: "SN",
    text: "Dalam membaca buku atau artikel, kamu lebih suka...",
    optionA: { text: "Step-by-step guide yang practical dan bisa langsung diterapkan", weight: "strong_a" },
    optionB: { text: "Ide-ide conceptual yang membuat kamu berpikir berbeda", weight: "strong_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 29,
    dimension: "SN",
    scenario: "Kamu memperhatikan seorang teman kamu terlihat murung.",
    text: "Kamu lebih fokus pada...",
    optionA: { text: "Apa yang kamu lihat — ekspresi wajah, bahasa tubuh, kejadian hari ini", weight: "strong_a" },
    optionB: { text: "Apa yang mungkin ada di baliknya — perasaan lebih dalam, pattern dari sebelumnya", weight: "strong_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 30,
    dimension: "SN",
    text: "Orang-orang sering describe kamu sebagai...",
    optionA: { text: "Practical, realistic, grounded", weight: "strong_a" },
    optionB: { text: "Imajinatif, abstract, visioner", weight: "strong_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 31,
    dimension: "SN",
    text: "Kalau kamu harus jelasin sesuatu ke orang lain, kamu biasanya...",
    optionA: { text: "Gunakan contoh konkret dan real-world examples", weight: "strong_a" },
    optionB: { text: "Jelaskan konsep besar dulu, lalu mungkin kasih contoh", weight: "strong_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 32,
    dimension: "SN",
    text: "Ketika berencana liburan, yang paling excited kamu adalah...",
    optionA: { text: "Itinerary konkret — tahu exactly di mana, makan apa, ke mana", weight: "slight_a" },
    optionB: { text: "Mbayangin experience dan vibes yang akan kamu rasakan", weight: "slight_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 33,
    dimension: "SN",
    text: "Dalam conversation, kamu lebih sering fokus pada...",
    optionA: { text: "Detail dan spesifik dari apa yang dibicarakan", weight: "strong_a" },
    optionB: { text: "Big picture dan connections antara ide-ide", weight: "strong_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 34,
    dimension: "SN",
    text: "Saat belajar skill baru, kamu lebih suka...",
    optionA: { text: "Practice langsung dengan contoh konkret", weight: "strong_a" },
    optionB: { text: "Pahami teori dan framework dulu baru practice", weight: "strong_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 35,
    dimension: "SN",
    text: "Kamu lebih trust...",
    optionA: { text: "Data dan evidence yang terukur", weight: "strong_a" },
    optionB: { text: "Gut feeling dan sixth sense kamu", weight: "strong_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 36,
    dimension: "SN",
    scenario: "Kamu diminta describe ruangan tempat kamu tinggal.",
    text: "Kamu lebih cenderung...",
    optionA: { text: "Describe detail fisiknya — ukuran, furniture, warna", weight: "strong_a" },
    optionB: { text: "Describe feel dan atmosphere — cozy, inspirational, moody", weight: "strong_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 37,
    dimension: "SN",
    text: "Kamu lebih enjoy...",
    optionA: { text: "Memperbarui dan meningkatkan hal-hal yang sudah ada", weight: "slight_a" },
    optionB: { text: "Menciptakan hal-hal yang benar-benar baru dari scratch", weight: "slight_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 38,
    dimension: "SN",
    text: "Dalam pekerjaan atau project, kamu lebih ingin tahu...",
    optionA: { text: "Langkah-langkah spesifik yang perlu dilakukan", weight: "strong_a" },
    optionB: { text: "Tujuan besar dan bagaimana ini fit dalam visi lebih besar", weight: "strong_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 39,
    dimension: "SN",
    text: "Kamu lebih interested dengan...",
    optionA: { text: "Apa yang ada sekarang dan apa yang sudah proven works", weight: "strong_a" },
    optionB: { text: "Apa yang bisa menjadi kenyataan di masa depan", weight: "strong_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 40,
    dimension: "SN",
    text: "Kamu lebih mudah mengingat...",
    optionA: { text: "Detail dan fakta spesifik dari kejadian", weight: "strong_a" },
    optionB: { text: "Kesan dan meaning dari kejadian secara keseluruhan", weight: "strong_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 41,
    dimension: "SN",
    text: "Kalau instruksi assembly furniture tidak jelas, kamu...",
    optionA: { text: "Frustrasi dan cari instruksi yang lebih jelas", weight: "strong_a" },
    optionB: { text: "Improvise berdasarkan logika dan feeling kamu", weight: "strong_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 42,
    dimension: "SN",
    text: "Saat mempertimbangkan ide baru, kamu pertama kali bertanya...",
    optionA: { text: "'Apakah ini realistic dan bisa dilaksanakan?'", weight: "strong_a" },
    optionB: { text: "'Apa possibilities yang bisa muncul dari ini?'", weight: "strong_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 43,
    dimension: "SN",
    text: "Kamu biasanya lebih comfortable dengan...",
    optionA: { text: "Pekerjaan yang memiliki clear procedures dan expectations", weight: "strong_a" },
    optionB: { text: "Pekerjaan yang open-ended dengan banyak ruang kreativitas", weight: "strong_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 44,
    dimension: "SN",
    text: "Dalam menjelaskan pengalaman, kamu cenderung...",
    optionA: { text: "Cerita secara kronologis dan detail", weight: "slight_a" },
    optionB: { text: "Jump ke part yang paling meaningful atau impactful", weight: "slight_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 45,
    dimension: "SN",
    text: "Kata mana yang paling resonates dengan kamu?",
    optionA: { text: "Konkret, Reliable, Present, Practical", weight: "strong_a" },
    optionB: { text: "Abstract, Innovative, Future, Metaphorical", weight: "strong_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 46,
    dimension: "SN",
    text: "Saat membuat keputusan besar, kamu biasanya...",
    optionA: { text: "Kumpulkan semua data dan fakta yang bisa kamu dapat", weight: "strong_a" },
    optionB: { text: "Bayangkan berbagai scenarios dan outcomes yang mungkin terjadi", weight: "strong_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 47,
    dimension: "SN",
    text: "Hobi atau aktivitas yang paling kamu enjoy adalah yang...",
    optionA: { text: "Melibatkan keahlian praktis — masak, olahraga, kerajinan", weight: "strong_a" },
    optionB: { text: "Melibatkan kreativitas abstrak — menulis, musik, imagine scenarios", weight: "strong_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 48,
    dimension: "SN",
    text: "Feedback yang kamu berikan pada orang lain biasanya...",
    optionA: { text: "Spesifik dan actionable — 'lakukan ini, hindari itu'", weight: "strong_a" },
    optionB: { text: "Conceptual — 'think about it dari angle ini'", weight: "strong_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 49,
    dimension: "SN",
    text: "Kamu lebih sering daydream tentang...",
    optionA: { text: "Rencana realistis untuk masa depan dekat", weight: "strong_a" },
    optionB: { text: "Possibilities yang masih jauh atau bahkan fantastis", weight: "strong_b" },
    labelA: "S",
    labelB: "N",
  },
  {
    id: 50,
    dimension: "SN",
    text: "Mana yang lebih kamu nilai dalam sebuah pekerjaan?",
    optionA: { text: "Execution yang excellence — lakukan dengan tepat dan benar", weight: "strong_a" },
    optionB: { text: "Innovation — menemukan cara baru yang belum pernah dicoba", weight: "strong_b" },
    labelA: "S",
    labelB: "N",
  },

  // ===== T/F DIMENSION (25 questions) =====
  {
    id: 51,
    dimension: "TF",
    text: "Saat membuat keputusan penting, kamu lebih rely pada...",
    optionA: { text: "Logika dan analisis objektif — apa yang paling makes sense", weight: "strong_a" },
    optionB: { text: "Nilai-nilai dan perasaan — apa yang feels right", weight: "strong_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 52,
    dimension: "TF",
    text: "Teman kamu minta pendapat jujur tentang keputusan yang kamu rasa salah. Kamu...",
    optionA: { text: "Kasih honest assessment meski mungkin tidak enak didengar", weight: "strong_a" },
    optionB: { text: "Pertimbangkan perasaan mereka dulu sebelum pilih kata-kata", weight: "strong_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 53,
    dimension: "TF",
    text: "Saat berdebat, kamu lebih concerned dengan...",
    optionA: { text: "Siapa yang logically correct", weight: "strong_a" },
    optionB: { text: "Menjaga hubungan tetap baik dan semua merasa heard", weight: "strong_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 54,
    dimension: "TF",
    scenario: "Sebuah kebijakan baru di tempat kerja sangat logis secara bisnis tapi berdampak buruk bagi beberapa karyawan.",
    text: "Reaksi pertama kamu...",
    optionA: { text: "Terima jika numbers dan logic mendukung — business is business", weight: "strong_a" },
    optionB: { text: "Concern dengan dampak manusianya dulu, perlu ada solusi yang lebih humanis", weight: "strong_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 55,
    dimension: "TF",
    text: "Kamu lebih mudah tersentuh oleh...",
    optionA: { text: "Argumen yang logis dan well-reasoned", weight: "slight_a" },
    optionB: { text: "Cerita yang emosional dan menyentuh hati", weight: "slight_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 56,
    dimension: "TF",
    text: "Ketika seseorang share masalahnya ke kamu, instinct pertama kamu adalah...",
    optionA: { text: "Bantu cari solusi dan analisis masalahnya", weight: "strong_a" },
    optionB: { text: "Listen dan validate perasaan mereka dulu", weight: "strong_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 57,
    dimension: "TF",
    text: "Orang-orang mungkin kadang bilang kamu...",
    optionA: { text: "Terlalu blunt atau dingin dalam deliver feedback", weight: "slight_a" },
    optionB: { text: "Terlalu sensitif atau ambil sesuatu terlalu personal", weight: "slight_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 58,
    dimension: "TF",
    text: "Dalam situasi konflik, kamu lebih fokus pada...",
    optionA: { text: "Mencari solusi yang logis dan fair untuk semua pihak", weight: "strong_a" },
    optionB: { text: "Memastikan semua orang merasa diperlakukan dengan baik dan didengar", weight: "strong_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 59,
    dimension: "TF",
    text: "Kalau kamu harus kasih kritik ke seseorang, kamu cenderung...",
    optionA: { text: "Direct dan clear — mereka perlu tahu masalahnya apa", weight: "strong_a" },
    optionB: { text: "Pilih kata-kata dengan hati-hati untuk minimize hurt feelings", weight: "strong_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 60,
    dimension: "TF",
    text: "Kamu lebih bangga dengan...",
    optionA: { text: "Deskripsi kamu sebagai 'smart dan kompeten'", weight: "slight_a" },
    optionB: { text: "Deskripsi kamu sebagai 'caring dan compassionate'", weight: "slight_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 61,
    dimension: "TF",
    text: "Saat menonton film sedih, kamu biasanya...",
    optionA: { text: "Bisa appreciate ceritanya tanpa harus ikut nangis", weight: "strong_a" },
    optionB: { text: "Ikut terbawa emosi — kamu mudah empathize dengan karakter", weight: "strong_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 62,
    dimension: "TF",
    text: "Dalam menilai situasi, kamu lebih sering bertanya...",
    optionA: { text: "'Apa yang benar secara logis?'", weight: "strong_a" },
    optionB: { text: "'Apa yang benar secara moral dan bagaimana ini affect orang?'", weight: "strong_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 63,
    dimension: "TF",
    text: "Kalau kamu tidak setuju dengan seseorang, kamu lebih nyaman...",
    optionA: { text: "Debat dan argue your point secara langsung", weight: "strong_a" },
    optionB: { text: "Find common ground dan hindari konflik yang tidak perlu", weight: "strong_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 64,
    dimension: "TF",
    text: "Kamu lebih mudah mengabaikan...",
    optionA: { text: "Perasaan kamu sendiri demi logical outcome yang lebih baik", weight: "strong_a" },
    optionB: { text: "Beberapa logika demi menjaga harmonisasi dan perasaan orang", weight: "strong_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 65,
    dimension: "TF",
    text: "Dalam mengambil keputusan di bawah tekanan, kamu biasanya...",
    optionA: { text: "Stay cool dan fokus pada facts — emosi bisa diproses nanti", weight: "strong_a" },
    optionB: { text: "Struggle antara logika dan perasaan tentang dampaknya", weight: "strong_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 66,
    dimension: "TF",
    text: "Teman kamu punya ide yang secara logis kemungkinan gagal. Kamu...",
    optionA: { text: "Kasih tahu dengan jelas kenapa idenya berisiko", weight: "strong_a" },
    optionB: { text: "Support enthusiasm mereka sambil pelan-pelan mention potential concerns", weight: "strong_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 67,
    dimension: "TF",
    text: "Dalam leadership, kamu lebih prioritaskan...",
    optionA: { text: "Hasil dan efisiensi — tim harus perform", weight: "strong_a" },
    optionB: { text: "Moral tim dan hubungan antar anggota", weight: "strong_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 68,
    dimension: "TF",
    text: "Kata-kata mana yang lebih describes kamu saat problem-solving?",
    optionA: { text: "Analytical, objective, systematic, efficient", weight: "strong_a" },
    optionB: { text: "Empathetic, harmonious, considerate, values-driven", weight: "strong_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 69,
    dimension: "TF",
    text: "Saat menerima feedback negatif, kamu cenderung...",
    optionA: { text: "Evaluate apakah feedback itu valid, kalau tidak — dismiss it", weight: "strong_a" },
    optionB: { text: "Terpengaruh secara emosional dulu sebelum bisa evaluate objectively", weight: "strong_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 70,
    dimension: "TF",
    text: "Kamu lebih sering membuat keputusan berdasarkan...",
    optionA: { text: "Konsistensi dengan prinsip dan logika", weight: "strong_a" },
    optionB: { text: "Circumstances dan siapa yang terlibat", weight: "strong_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 71,
    dimension: "TF",
    text: "Dalam project kelompok, kamu lebih sering berperan sebagai...",
    optionA: { text: "Yang memastikan pekerjaan selesai dengan benar dan efisien", weight: "strong_a" },
    optionB: { text: "Yang menjaga dynamics tim tetap baik dan semua merasa included", weight: "strong_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 72,
    dimension: "TF",
    text: "Kamu lebih mudah forgive seseorang kalau...",
    optionA: { text: "Mereka punya alasan logis yang valid", weight: "strong_a" },
    optionB: { text: "Mereka tulus minta maaf dan menunjukkan empati", weight: "strong_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 73,
    dimension: "TF",
    text: "Waktu kamu jarang ada yang minta tolong, kamu merasa...",
    optionA: { text: "Efficient — orang bisa handle their own problems", weight: "strong_a" },
    optionB: { text: "Sedikit worried — apa orang okay? Apa mereka tidak comfortable ke kamu?", weight: "strong_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 74,
    dimension: "TF",
    text: "Dalam sebuah argumen yang intense, kamu biasanya...",
    optionA: { text: "Tetap cool dan fokus pada facts bahkan kalau yang lain emosi", weight: "strong_a" },
    optionB: { text: "Ikut terpengaruh secara emosional meski kamu tahu itu tidak ideal", weight: "strong_b" },
    labelA: "T",
    labelB: "F",
  },
  {
    id: 75,
    dimension: "TF",
    text: "Kamu lebih sering regret karena...",
    optionA: { text: "Terlalu mempertimbangkan perasaan orang sehingga tidak bisa buat keputusan tegas", weight: "strong_a" },
    optionB: { text: "Terlalu blunt atau tidak cukup mempertimbangkan dampak emosional keputusan kamu", weight: "strong_b" },
    labelA: "T",
    labelB: "F",
  },

  // ===== J/P DIMENSION (25 questions) =====
  {
    id: 76,
    dimension: "JP",
    text: "Meja atau ruangan kamu cenderung...",
    optionA: { text: "Teratur — semua ada tempatnya dan kamu tahu di mana", weight: "strong_a" },
    optionB: { text: "Kreatif chaos — terlihat berantakan tapi kamu tahu sistem kamu sendiri", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 77,
    dimension: "JP",
    text: "Saat ada project dengan deadline jauh, kamu biasanya...",
    optionA: { text: "Mulai plan dari sekarang dan cicil dengan structured schedule", weight: "strong_a" },
    optionB: { text: "Mulai nanti ketika sudah terasa urgent atau inspirasi datang", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 78,
    dimension: "JP",
    text: "Kamu lebih enjoy...",
    optionA: { text: "Checklist — ada kepuasan tersendiri mencentang item selesai", weight: "strong_a" },
    optionB: { text: "Flexible flow — lihat bagaimana hari berjalan tanpa terlalu terikat list", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 79,
    dimension: "JP",
    text: "Ketika rencana mendadak berubah, kamu biasanya...",
    optionA: { text: "Stress dulu — kamu butuh penyesuaian sebelum bisa adapt", weight: "strong_a" },
    optionB: { text: "Adaptable — perubahan mendadak sering malah exciting", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 80,
    dimension: "JP",
    text: "Saat mengerjakan tugas, kamu cenderung...",
    optionA: { text: "Fokus selesaikan satu hal sebelum lanjut ke yang lain", weight: "strong_a" },
    optionB: { text: "Juggle beberapa hal sekaligus dan switch sesuai mood dan energi", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 81,
    dimension: "JP",
    text: "Liburan ideal kamu adalah...",
    optionA: { text: "Terencana dengan baik — booking hotel, itinerary, reservasi makan", weight: "strong_a" },
    optionB: { text: "Spontan — tahu tujuan utama, sisanya figure out along the way", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 82,
    dimension: "JP",
    text: "Saat kamu punya banyak pilihan, kamu biasanya...",
    optionA: { text: "Evaluasi dan ambil keputusan secepat mungkin — terlalu banyak options stressful", weight: "strong_a" },
    optionB: { text: "Enjoy mengeksplorasi semua options sebelum commit", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 83,
    dimension: "JP",
    text: "Di tempat kerja, kamu lebih suka...",
    optionA: { text: "Clear expectations, deadlines, dan struktur yang jelas", weight: "strong_a" },
    optionB: { text: "Flexibility dan otonomi dalam cara kamu bekerja", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 84,
    dimension: "JP",
    text: "Perasaan kamu setelah project selesai...",
    optionA: { text: "Puas dan bisa fully move on ke hal berikutnya", weight: "strong_a" },
    optionB: { text: "Sedikit tidak karuan — kamu suka proses pengerjaannya", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 85,
    dimension: "JP",
    text: "Rutinitas harian kamu...",
    optionA: { text: "Konsisten — ada struktur yang kamu ikuti karena itu efisien", weight: "strong_a" },
    optionB: { text: "Fleksibel — tiap hari bisa berbeda sesuai situasi dan mood", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 86,
    dimension: "JP",
    text: "Saat dinner bareng teman, kamu biasanya yang...",
    optionA: { text: "Riset tempat makan dulu dan tentukan sebelum ketemu", weight: "strong_a" },
    optionB: { text: "Enjoy figuring out spontan waktu sudah ketemu", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 87,
    dimension: "JP",
    text: "Kamu lebih sering delayed karena...",
    optionA: { text: "Overthinking dan overplanning sebelum mulai action", weight: "strong_a" },
    optionB: { text: "Start terlalu banyak hal dan sulit focus untuk finish", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 88,
    dimension: "JP",
    text: "Approach kamu terhadap deadline...",
    optionA: { text: "Deadline adalah komitmen — kamu selalu on time atau lebih awal", weight: "strong_a" },
    optionB: { text: "Deadline adalah guideline — kamu bekerja paling baik under pressure", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 89,
    dimension: "JP",
    text: "Kalau kamu punya free day dengan no obligation, kamu lebih suka...",
    optionA: { text: "Punya rencana untuk isi hari itu — ada yang ingin diselesaikan", weight: "strong_a" },
    optionB: { text: "Biarkan mengalir — lihat apa yang menarik pada saat itu", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 90,
    dimension: "JP",
    text: "Inbox email atau chat kamu...",
    optionA: { text: "Biasanya organized dan di-reply tepat waktu", weight: "strong_a" },
    optionB: { text: "Bisa menumpuk — kamu reply ketika kamu bisa dan punya energi", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 91,
    dimension: "JP",
    text: "Dalam membuat rencana jangka panjang...",
    optionA: { text: "Kamu suka punya clear milestones dan action plan yang detailed", weight: "strong_a" },
    optionB: { text: "Kamu tahu destination besar tapi suka flexibility dalam cara mencapainya", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 92,
    dimension: "JP",
    text: "Saat mengemasi barang untuk pindahan atau liburan...",
    optionA: { text: "Kamu buat list apa yang perlu dibawa dan pack systematic", weight: "strong_a" },
    optionB: { text: "Kamu pack berdasarkan apa yang kamu ingat dan butuh, tanpa list formal", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 93,
    dimension: "JP",
    text: "Kalau ada task yang tidak perlu deadline, kamu biasanya...",
    optionA: { text: "Buat deadline sendiri — tanpa itu kamu tidak efisien", weight: "strong_a" },
    optionB: { text: "Kerjakan sesuai mood — kalau tidak urgent, bisa nanti", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 94,
    dimension: "JP",
    text: "Saat berbelanja, kamu biasanya...",
    optionA: { text: "Datang dengan list yang jelas dan sticking to it", weight: "strong_a" },
    optionB: { text: "Browse dulu dan beli apa yang menarik atau spontan diperlukan", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 95,
    dimension: "JP",
    text: "Ketika kamu tahu ada sesuatu yang perlu diputuskan, kamu cenderung...",
    optionA: { text: "Settle it ASAP — uncertainty bikin tidak nyaman", weight: "strong_a" },
    optionB: { text: "Biarkan open dulu — mungkin ada informasi baru yang datang", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 96,
    dimension: "JP",
    text: "Saat kamu interrupt di tengah task penting, kamu...",
    optionA: { text: "Annoys kamu — kamu perlu selesaikan apa yang sedang dikerjakan dulu", weight: "strong_a" },
    optionB: { text: "Oke aja — kamu adaptable dan bisa back to task setelahnya", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 97,
    dimension: "JP",
    text: "Mana yang lebih describe cara kamu bekerja?",
    optionA: { text: "Systematic, planned, organized, closure-oriented", weight: "strong_a" },
    optionB: { text: "Adaptive, spontaneous, open, exploration-oriented", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 98,
    dimension: "JP",
    text: "Saat kamu janji dengan seseorang, kamu biasanya...",
    optionA: { text: "On time atau lebih awal — being late is disrespectful", weight: "strong_a" },
    optionB: { text: "Honestly kadang sedikit terlambat meski kamu berusaha", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 99,
    dimension: "JP",
    text: "Perasaan kamu tentang options yang masih open...",
    optionA: { text: "Lebih nyaman ketika sudah ada keputusan — closure is good", weight: "strong_a" },
    optionB: { text: "Enjoy keeping options open — you never know what might come up", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
  {
    id: 100,
    dimension: "JP",
    text: "Secara keseluruhan, kamu lebih describe dirimu sebagai...",
    optionA: { text: "Terencana, structured, prefer tahu apa yang akan terjadi", weight: "strong_a" },
    optionB: { text: "Spontan, fleksibel, enjoy surprise dan open endings", weight: "strong_b" },
    labelA: "J",
    labelB: "P",
  },
];

export const WEIGHT_SCORES = {
  strong_a: 3,
  slight_a: 1,
  neutral: 0,
  slight_b: -1,
  strong_b: -3,
};

// Randomly select n questions from a dimension pool
export const getRandomQuestions = (count: number = 60): Question[] => {
  const byDimension: Record<Dimension, Question[]> = {
    EI: QUESTIONS.filter((q) => q.dimension === "EI"),
    SN: QUESTIONS.filter((q) => q.dimension === "SN"),
    TF: QUESTIONS.filter((q) => q.dimension === "TF"),
    JP: QUESTIONS.filter((q) => q.dimension === "JP"),
  };

  const perDimension = Math.floor(count / 4);
  const selected: Question[] = [];

  (Object.keys(byDimension) as Dimension[]).forEach((dim) => {
    const pool = [...byDimension[dim]];
    const shuffled = pool.sort(() => Math.random() - 0.5);
    selected.push(...shuffled.slice(0, perDimension));
  });

  return selected.sort(() => Math.random() - 0.5);
};
